### ISSUE TITLE
When in FPFC doesn't allow to get out of Replays

### ISSUE THREAD

**Issue by SyncBS** [rynan4818/HttpPlayButtonStatus#1]
When I have the game in fpfc mode I am unable to quit out of a ScoreSaber Replay when I have this mod installed.

This does not happen every time, only when sometimes the mod itself stops working and does not change to OBS Game Scene while entering Replay.

Here is a video of what happens as well as my log files:

I enter Replay, it doesn't change Scene in OBS and I can't click Menu or Restart on the Replay.
https://youtu.be/amRbVAY82p4

[2022.09.14.23.44.20.log](https://github.com/rynan4818/HttpPlayButtonStatus/files/9570453/2022.09.14.23.44.20.log)

**Comment by SyncBS** [comment]
After further inspection I have understood that if you go into a replay after starting the game it will not work.

BUT if you go into a Map and back out then you are allowed to use replays as usual.

**Comment by rynan4818** [comment]
Thank you for your report.

We have confirmed the reproduction of the problem and have identified the cause.

We have released a corrected [v0.1.1](https://github.com/rynan4818/HttpPlayButtonStatus/releases/tag/v0.1.1), please check it.

If the problem persists, please contact us again.
